export const COLOR_SCHEMES = [
    {
      name: "Professional Blue",
      primary: "#3490dc",
      secondary: "#4fd1c5",
      dark: "#2d3748",
      light: "#f8fafc",
      background: "#ffffff",
      card: "#f4f4f4",
      muted: "#f1f5f9",
      accent: "#e0e7ff",
      fontHeading: "Montserrat",
      fontBody: "Open Sans",
      body: "#1a202c",
    },
    {
      name: "Creative Purple",
      primary: "#9f7aea",
      secondary: "#f687b3",
      dark: "#322659",
      light: "#faf5ff",
      background: "#f8f0fc",
      card: "#f3e8ff",
      muted: "#e9d8fd",
      accent: "#b794f4",
      fontHeading: "Poppins",
      fontBody: "Lato",
      body: "#1a202c",
    },
    {
      name: "Modern Green",
      primary: "#38a169",
      secondary: "#ecc94b",
      dark: "#22543d",
      light: "#f0fff4",
      background: "#e6fffa",
      card: "#c6f6d5",
      muted: "#f0fff4",
      accent: "#68d391",
      fontHeading: "Nunito",
      fontBody: "Roboto",
      body: "#1a202c",
    },
    {
      name: "Bold Red",
      primary: "#e53e3e",
      secondary: "#ed8936",
      dark: "#742a2a",
      light: "#fff5f5",
      background: "#fffaf0",
      card: "#fed7d7",
      muted: "#fff5f5",
      accent: "#f56565",
      fontHeading: "Oswald",
      fontBody: "Open Sans",
      body: "#1a202c",
    },
    {
      name: "Elegant Grey",
      primary: "#718096",
      secondary: "#f56565",
      dark: "#2d3748",
      light: "#f7fafc",
      background: "#f1f5f9",
      card: "#e2e8f0",
      muted: "#edf2f7",
      accent: "#a0aec0",
      fontHeading: "Merriweather",
      fontBody: "Lato",
      body: "#1a202c",
    },
    {
      name: "Dark Mode",
      primary: "#6366f1",
      secondary: "#8b5cf6",
      dark: "#111827",
      light: "#e5e7eb",
      background: "#1f2937",
      card: "#374151",
      muted: "#4b5563",
      accent: "#5eead4",
      fontHeading: "Inter",
      fontBody: "Roboto",
      body: "#e5e7eb",
    },
    {
      name: "Midnight Blue",
      primary: "#60a5fa",
      secondary: "#34d399",
      dark: "#0f172a",
      light: "#e2e8f0",
      background: "#1e293b",
      card: "#334155",
      muted: "#475569",
      accent: "#f472b6",
      fontHeading: "Outfit",
      fontBody: "Source Sans Pro",
      body: "#e5e7eb",
    },
  ];
  